In [1]:
import numpy as np
np.__version__

'1.24.2'

In [2]:
l=[10,20,30,40,50]
type(l)

list

In [3]:
arr=np.array(l)

In [4]:
type(arr)

numpy.ndarray

In [5]:
print(arr+2)

[12 22 32 42 52]


In [6]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', '

In [7]:
print(arr)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.shape)


[10 20 30 40 50]
1
5
int64
(5,)


In [8]:
arr_f=np.array((arr),dtype=float)

In [9]:
print(arr_f)

[10. 20. 30. 40. 50.]


In [10]:
arr_str=np.array((arr),dtype=str)
print(arr_str)

['10' '20' '30' '40' '50']


In [11]:
arr_ar = np.arange(1,16)
print(arr_ar)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [12]:
print(arr_ar.dtype)

int64


In [13]:
arr = np.arange(20,1,-1)
print(arr)

[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2]


In [14]:
print(np.zeros(3))

[0. 0. 0.]


In [15]:
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [16]:
print(np.zeros((2,3,5)))

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [17]:
print(np.ones((2,3,5)))

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [18]:
print(np.full((2,3,5),4))

[[[4 4 4 4 4]
  [4 4 4 4 4]
  [4 4 4 4 4]]

 [[4 4 4 4 4]
  [4 4 4 4 4]
  [4 4 4 4 4]]]


In [19]:
# Arithmatic Operators
arr = np.array([10,20,30,40])
# print(arr+2)
# print(arr-2)
# print(arr*2)
# print(arr/2)
# print(arr+2)

In [20]:
a = np.array([[10,20],[30,40],[50,60]])
b = np.array([10,20])

# print(a+b)
# print(a-b)
print(a*b)
print(a/b)
print(a%b)

[[ 100  400]
 [ 300  800]
 [ 500 1200]]
[[1. 1.]
 [3. 2.]
 [5. 3.]]
[[0 0]
 [0 0]
 [0 0]]


In [21]:
a = np.arange(1,6)
a
b= np.resize(a,[3,3])
print(b)

[[1 2 3]
 [4 5 1]
 [2 3 4]]


In [24]:
# a = np.arange(1,28).reshape(3,3,3)
# b = a.flatten()
# print(b)

a = np.arange(1,10)
a.shape
b = a.reshape(3,3)
b.shape
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
